// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Fixrebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXHp0u_iY39JWgPIybD_WGm3bQvbiRy3E',
    appId: '1:512690567235:web:b70ddd81ce60fd1bdffcf6',
    messagingSenderId: '512690567235',
    projectId: 'note-919c5',
    authDomain: 'note-919c5.firebaseapp.com',
    storageBucket: 'note-919c5.firebasestorage.app',
    measurementId: 'G-BPCMFSTESB',
    databaseURL: 'https://note-919c5-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtgkziolvU-N28r5q_o7c5b31wmR2AMs',
    appId: '1:512690567235:android:804334eca5a64a1cdffcf6',
    messagingSenderId: '512690567235',
    projectId: 'note-919c5',
    storageBucket: 'note-919c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3shmVyOhdhOYUNet6cP1ZsUasSTU0fg',
    appId: '1:512690567235:ios:a5ba4e365970e594dffcf6',
    messagingSenderId: '512690567235',
    projectId: 'note-919c5',
    storageBucket: 'note-919c5.firebasestorage.app',
    iosBundleId: 'com.example.demoappprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr3shmVyOhdhOYUNet6cP1ZsUasSTU0fg',
    appId: '1:512690567235:ios:a5ba4e365970e594dffcf6',
    messagingSenderId: '512690567235',
    projectId: 'note-919c5',
    storageBucket: 'note-919c5.firebasestorage.app',
    iosBundleId: 'com.example.demoappprovider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXHp0u_iY39JWgPIybD_WGm3bQvbiRy3E',
    appId: '1:512690567235:web:99466d7eb8d5c05cdffcf6',
    messagingSenderId: '512690567235',
    projectId: 'note-919c5',
    authDomain: 'note-919c5.firebaseapp.com',
    storageBucket: 'note-919c5.firebasestorage.app',
    measurementId: 'G-861RQW6VTL',
  );
}
